### ISSUE TITLE
Secret store is going to different realm api endpoint otherthen DRCC realm api endpoint

### ISSUE THREAD

**Issue by bkumar73** [oracle-samples/oci-secrets-store-csi-driver-provider#10]
Hi Team,

We are trying to set up OCI-Secrets-store-csi driver in DRCC OKE, but when Application deployment tries to access secret in DRCC Oci Vault, it's going to the wrong realm API endpoint for Authentication.
Please find below the error message

Warning   FailedMount         pod/keep-secrets-alive-97dd8bf5b-hwttl     MountVolume.SetUp failed for volume "bootstrap-reposecrets" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod argocd/keep-secrets-alive-97dd8bf5b-hwttl, err: rpc error: code = NotFound desc = unable to retrieve secrets: can not create client, bad configuration: failed to get security token: failed to renew security token: failed to get security token: failed to call: Post "https://auth.xx-dcc-<customregion).oraclecloud.com/v1/x509": dial tcp: lookup auth.xx-<customregion>.oraclecloud.com on 10.96.5.5:53:

Note: this endpoint URL should have been auth.xx-dcc-<customregion>.oraclecloud-realmnumber.com

Kindly suggest, how can we define our realm API endpoint within OCI secret store.

Thanks,
Brajesh Kumar

**Comment by rajashekhargundeti** [comment]
@YashwantGohokar,  Can you look into this.

**Comment by rajashekhargundeti** [comment]
Addressed it with [release](https://github.com/oracle-samples/oci-secrets-store-csi-driver-provider/releases/tag/v0.1.0) 

Please use the attached assets of the release to get the new image.
