### ISSUE TITLE
The conflicted manifest file is committed

### ISSUE THREAD

**Issue by tniita** [oracle-samples/oci-secrets-store-csi-driver-provider#3]
[This file](https://github.com/oracle-samples/oci-secrets-store-csi-driver-provider/tree/main/deploy/provider.daemonset.yaml) seems to be conflicted.(from line 48 to 64)
This should be fixed ASAP.

**Comment by rajashekhargundeti** [comment]
Hi Takuya,
I have corrected the merge issue.
Please check and let me know if we can close this issue

**Comment by rajashekhargundeti** [comment]
Resolved merge conflicts
